version: 0.0
os: linux
files:
#tallentaa t채h채n /python_demo kansioon kaiken mit채 lataa esim p채ivityksen mukana
  - source: /
    destination: /home/ec2-user/python_demo
hooks:
  BeforeInstall:
    - location: install_dependencies.sh
      timeout: 200
      runas: root

  ApplicationStart:
    - location: sripts/run_http.sh
      timeout: 200

  ApplicationStop:
    - location: sripts/stop_http.sh
      timeout: 200